from django.urls import path
from .views import *
from . import views
from django.contrib import admin

app_name = 'sisventas'
urlpatterns = [
    path('', views.loginpage, name='login'),
    path('admin/', admin.site.urls),
    path('logout/', views.logout_view, name='logout'),
    path('inicio/', views.base, name='base'),
    path('pos/', views.pos, name='pos_system'),
    path('document/<int:sale_id>', views.document, name='document'),
    path('search-products/', views.search_products, name='search-products'),
    path('search-inventory/', views.search_inventory, name='search-inventory'),
    path('formprod/', views.form_product, name='form_prod'),
    path('delete/<int:id>/', views.form_product_delete, name='prod_delete'),
    path('edit/<int:id>/', views.form_product_edit, name='prod_edit'),
    path('addcart/<int:id>/', views.add_product_cart, name='add_cart'),
    path('remove/<int:id>/', views.remove_product_cart, name='remove_cart'),
    path('updatecart/<int:id>/', views.update_cart, name='update_cart'),
    path('clear/', views.clear_cart, name='clear_cart'),
    path('confirm/', views.confirm_sale, name='confirm_sale'),
    path('formclient/', views.form_client, name='form_client'),
    path('deleteclient/<str:rut>/', views.form_client_delete, name='client_delete'),
    path('editclient/<str:rut>/', views.form_client_edit, name='client_edit'),
    path('search-client/', views.search_client, name='search-client'),
    path('sales_jefe_ventas/', views.sales_jefe_ventas, name='sales_jefe_ventas'),
    path('sales_vendedor/', views.sales_vendedor, name='sales_vendedor'),
    path('search-sale/', views.search_sale, name='search-sale'),
    path('sale_detail/<int:sale_id>', views.sale_detail, name='sale_detail'),
    path('refund/', views.refund, name='refund'),
    path('change_product/<int:sale_id>/',
         views.change_product, name='change_product'),
    path('change_product/', views.change_product, name='change_product_no_id'),
    path('search-change/', views.search_products_change, name='search_in_change'),
    path('genre/', views.genre, name='genre'),
    path('genre_delete/<int:id>/', views.genre_delete, name='genre_delete'),
    path('genre_edit/<int:id>/', views.genre_edit, name='genre_edit'),
    path('region_delete/<int:id>/', views.region_delete, name='region_delete'),
    path('region_edit/<int:id>/', views.region_edit, name='region_edit'),
    path('ciudad_delete/<int:id>/', views.ciudad_delete, name='ciudad_delete'),
    path('ciudad_edit/<int:id>/', views.ciudad_edit, name='ciudad_edit'),
    path('comuna_delete/<int:id>/', views.comuna_delete, name='comuna_delete'),
    path('comuna_edit/<int:id>/', views.comuna_edit, name='comuna_edit'),
    path('form_location/', views.form_location, name='form_location'),
    path('jefe_ventas/', views.jefe_ventas, name='jefe_ventas'),
    path('jefe_search/', views.search_jefe_ventas, name='jefe_search'),
    path('auth/', views.auth, name='auth'),
    path('authorization/', views.authorization, name='authorization'),
    path('delete_sale_id/', views.delete_sale_id, name='delete_sale_id'),
    path('start_sale/', views.start_day, name='start_sale'),
    path('end_sale/', views.end_day, name='end_sale'),
    path('form_employee/', views.form_employee, name='form_employee'),
    path('edit_employee/<str:rut>/',
         views.form_employee_edit, name='edit_employee'),
    path('delete_employee/<str:rut>/',
         views.form_employee_delete, name='delete_employee'),
    path('profile/', views.profile, name='profile'),
    path('profile_edit/<int:id>', views.profile_edit, name='edit_profile'),
    path('profile_delete/<int:id>', views.profile_delete, name='delete_profile'),
    path('iva/', views.iva, name='iva'),
    path('iva_edit/<int:id>/', views.iva_edit, name='iva_edit'),
    path('iva_delete/<int:id>/', views.iva_delete, name='iva_delete'),
    path('registro_empleados/', views.working_hours, name='registro_empleados'),
    path('credentials/', views.change_credentials, name='credentials'),
    path('return_page/', views.return_page, name='return_page'),
    path('sales_report/', views.sales_report, name='sales_report'),
    path('open_close/', views.open_close_list, name='open_close'),

]
