# Generated by Django 4.2.1 on 2023-07-04 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la comuna')),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sisventas.city', verbose_name='ID de la ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del documento')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='IVA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(verbose_name='Porcentaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Correo electrónico')),
                ('street', models.CharField(max_length=50, verbose_name='Calle')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Razón social')),
                ('giro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Giro')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Empleado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sisventas.city', verbose_name='Ciudad')),
                ('id_commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sisventas.commune', verbose_name='Comuna')),
                ('id_genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sisventas.genre', verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de producto')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('unit_price', models.IntegerField(verbose_name='Precio unitario')),
                ('add_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('expiration_date', models.DateField(verbose_name='Fecha de expiración')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Oculto')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la región')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('hour', models.TimeField(verbose_name='Hora')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('is_refund', models.BooleanField(default=False, verbose_name='Devolución')),
                ('original_sale_id', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Client', to='sisventas.person', verbose_name='Cliente')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sisventas.document', verbose_name='ID del documento')),
                ('iva_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sisventas.iva', verbose_name='Porcentaje del IVA')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Seller', to='sisventas.person', verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField(verbose_name='Cantidad del producto')),
                ('unit_price', models.IntegerField(verbose_name='Precio unitario')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('original_sale_id', models.IntegerField(blank=True, null=True)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sisventas.product', verbose_name='ID del producto')),
                ('id_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sisventas.sale', verbose_name='ID de la venta')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='id_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sisventas.profile', verbose_name='ID del perfil'),
        ),
        migrations.AddField(
            model_name='person',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sisventas.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='OpeningClosing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('is_open', models.BooleanField(default=False, verbose_name='¿Está abierto?')),
                ('closing_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closings', to='sisventas.person', verbose_name='Empleado que cerró')),
                ('opening_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings', to='sisventas.person', verbose_name='Empleado que abrió')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_time_sesion', models.TimeField(verbose_name='Hora de inicio de la sesión')),
                ('closing_time_sesion', models.TimeField(null=True, verbose_name='Hora de cierre de la sesión')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('rut_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sisventas.person', verbose_name='Rut del empleado')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sisventas.region', verbose_name='ID de la región'),
        ),
    ]
